name: Attest

on:
  push:
    tags: ['[0-9]*.[0-9]*.[0-9]*']

permissions:
  contents: read

jobs:
  attest:
    name: Build provenance
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Attest the Composer package
        uses: k2gl/composer-attest-action@v1
